#!/bin/bash

GIT_TP_LOC=~/tp-2015-2c-elclan
PLANIFICADOR=Planificador

#CONFIGURE PARAMETERS OF PLANIFICADOR PROCESS
clear

cd $GIT_TP_LOC/$PLANIFICADOR
rm Planificador.config

echo "SE VA A INICIAR EL PROCESO PLANIFICADOR"
echo "INGRESE EL PUERTO ESCUCHA PARA LA CONEXION CON CPUS"
read PTO_CPU
echo "INGRESE EL ALGORITMO DE PLANIFICACION"
read ALGORITMO_PLANIFICACION
echo "INGRESE EL QUANTUM A USAR (0 PARA FIFO)"
read QUANTUM

echo "PUERTO_ESCUCHA=$PTO_CPU">>  $GIT_TP_LOC/$PLANIFICADOR/Planificador.config
echo "ALGORITMO_PLANIFICACION=$ALGORITMO_PLANIFICACION">>  $GIT_TP_LOC/$PLANIFICADOR/Planificador.config
echo "QUANTUM=$QUANTUM">>  $GIT_TP_LOC/$PLANIFICADOR/Planificador.config

#Execute Planificador
clear

echo "EXECUTING PLANIFICADOR"

cd $GIT_TP_LOC/$PLANIFICADOR

./$PLANIFICADOR Planificador.config
