#!/bin/bash

GIT_TP_LOC=~/git/tp-2015-2c-elclan/
CPUS=Cpu

#CONFIGURE PARAMETERS OF CPU PROCESS
clear
echo "SE VA A INICIAR EL PROCESO CPU"
echo "INGRESE LA IP DEL PROCESO PLANIFICADOR"
read IP_PLANIFICADOR
echo "INGRESE EL PUERTO DEL PROCESO PLANIFICADOR"
read PUERTO_PLANIFICADOR
echo "INGRESE LA IP DEL PROCESO MEMORIA"
read IP_MEMORIA
echo "INGRESE EL PUERTO DEL PROCESO MEMORIA"
read PUERTO_MEMORIA
echo "INGRESE LA CANTIDAD DE HILOS NECESARIOS"
read CANTIDAD_HILOS
echo "INGRESE EL RETARDO A APLICAR"
read RETARDO

echo "IP_PLANIFICADOR=$IP_PLANIFICADOR">>  $GIT_TP_LOC/$CPUS/cpu.config
echo "PUERTO_PLANIFICADOR=$PUERTO_PLANIFICADOR">>  $GIT_TP_LOC/$CPUS/cpu.config
echo "IP_MEMORIA=$IP_MEMORIA">>  $GIT_TP_LOC/$CPUS/cpu.config
echo "PUERTO_MEMORIA=$PUERTO_MEMORIA">>  $GIT_TP_LOC/$CPUS/cpu.config
echo "CANTIDAD_HILOS=$CANTIDAD_HILOS">>  $GIT_TP_LOC/$CPUS/cpu.config
echo "RETARDO=$RETARDO">>  $GIT_TP_LOC/$CPUS/cpu.config

#Execute CPU

echo "EXECUTING CPU"

cd $GIT_TP_LOC/$CPUS

clear

./$CPUS cpu.config